<a href="https://colab.research.google.com/github/HarisJafri-xcode/Data-Analyst-in-Python/blob/main/Introduction-to-Python/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

In [ ]:
# 2 Lists
height = [1.73, 1.68, 1.71]
weight = [65.4, 59.2, 63.6]

In [ ]:
# Quick BMI Calculation is impossible
# weight/(height**2) --> throws an Error

In [ ]:
# Importing NumPy Package
import numpy as np

In [ ]:
# Converting Lists into ndArrays
np_height = np.array(height)
np_weight = np.array(weight)

In [ ]:
# Deriving element wise BMI
bmi = np_weight / (np_height**2)
print(bmi)

[21.85171573 20.97505669 21.75028214]


In [ ]:
# Heterogeneous List
l = [1,2,3.5,"hi"]

# converting into ndArray
np_l = np.array(l)
print(np_l)

['1' '2' '3.5' 'hi']


In [ ]:
# List and ndArray
python_list = [1,2,3]
numpy_array = np.array([1,2,3])

# Lists appends when added
print(python_list + python_list)

# ndArrays add when added
print(numpy_array + numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
# ndArray of Scores
scores = np.array([23, 54, 75, 89, 12, 29])

In [ ]:
# indexing Element 0
print(scores[0])

23


In [ ]:
# Slicing Element 1 to 4
print(scores[1:5])

[54 75 89 12]


In [ ]:
# Comparison Operator
scores>50

array([False,  True,  True,  True, False, False])

In [ ]:
# Elements greater than 50
print(scores[scores>50])

[54 75 89]


# 2D Arrays

In [ ]:
# type of NumPy Array
type(scores)

numpy.ndarray

In [ ]:
# Creating 2D Arrays with 3 Lists inside a List
np_2d = np.array([[55, 21, 23, 89, 51], [12, 25, 56, 78, 45], [53, 22, 47, 58, 99]])

In [ ]:
# Applying .shape method
np_2d.shape

(3, 5)

In [ ]:
# Printing Array
print(np_2d)

[[55 21 23 89 51]
 [12 25 56 78 45]
 [53 22 47 58 99]]


In [ ]:
# Indexing Row 0
print(np_2d[0])

[55 21 23 89 51]


In [ ]:
# Indexing Row 1
print(np_2d[1])

[12 25 56 78 45]


In [ ]:
# Indexing Row 2
print(np_2d[2])

[53 22 47 58 99]


In [ ]:
# Indexing Scaler at Row 0 Column 1
print(np_2d[0,1])

21


In [ ]:
# Indexing Scaler at Row 2 Column 3
print(np_2d[2,3])

58


In [ ]:
# Indexing Scaler at Row 1 Column 2
print(np_2d[1,2])

56


In [ ]:
# Slicing Rows 0 to 1
print(np_2d[0:2])

[[55 21 23 89 51]
 [12 25 56 78 45]]


In [ ]:
# Slicing Rows from Start till End
print(np_2d[:])

[[55 21 23 89 51]
 [12 25 56 78 45]
 [53 22 47 58 99]]


In [ ]:
# Slicing R0 to R1, C1 to C2
print(np_2d[0:2, 1:3])

[[21 23]
 [25 56]]


In [ ]:
# Slicing R1 to End, Start to C1
print(np_2d[1:, :2])

[[12 25]
 [53 22]]


In [ ]:
# Indexing and Slicing
print(np_2d[0,1:4])

[21 23 89]


In [ ]:
# Indexing and Slicing
print(np_2d[0:2,1])

[21 25]


In [ ]:
# All Elements greater than 50
print(np_2d[np_2d>50])

[55 89 51 56 78 53 58 99]


In [ ]:
# All Even Elements
print(np_2d[(np_2d%2)==0])

[12 56 78 22 58]


# Basic Statistics

In [ ]:
# Sum of all Elements
print(np.sum(np_2d))

734


In [ ]:
# Max out of all Elements
print(np.max(np_2d))

99


In [ ]:
# Min out of all Elements
print(np.min(np_2d))

12


In [ ]:
# Average of all Elements
print(np.mean(np_2d))

48.93333333333333


In [ ]:
# St. Dev of all Elements
print(np.std(np_2d))

24.87426157474607


In [ ]:
# Variance of all Elements
print(np.var(np_2d))

618.7288888888888


In [ ]:
# Max of Index 1 Row
print(np.max(np_2d[1]))

78


In [ ]:
# Min of Index 2 Column
print(np.min(np_2d[:,2]))

23


In [ ]:
# Squash the Rows
np.max(np_2d, axis=0)

array([55, 25, 56, 89, 99])

In [ ]:
# Squash the Columns and don't drop dimension
np.min(np_2d, axis=1, keepdims=True)

array([[21],
       [12],
       [22]])